# key? 32byte (256bit)
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012




#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/examplesdb?useUnicode=true&serverTimezone=Asia/Seoul
#    username: urstory
#    password: u1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
---
# DATABASE
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local
  driverClassName: org.h2.Driver
  username: sa
  password:
# JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect